---
# tasks file for nxrm3-api

- include: run.yml


# - name: Run NXRM3 API script
#   uri:
#     url: "{{ nxrm3_item.host }}:{{ nxrm3_item.port }}/{{ nxrm3_api_endpoint }}"
#     user: "{{ nxrm3_item.user }}"
#     password: "{{ nxrm3_item.passwd }}"
#     headers:
#       Content-Type: "application/json"
#     method: POST
#     status_code: 200,204
#     force_basic_auth: yes
#     body: "{{ api_body | to_json }}"
#     body_format: json
#   loop: "{{ nxrm3_instances }}"
#   loop_control:
#      loop_var: nxrm3_item
#   register: op

# - debug:
#     var: op

# - debug:
#     var: api_body

# - debug:
#     var: nxrm3_api_endpoint
  